name: CI - Dashboards tests (task_0 → task_9)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    name: Task ${{ matrix.task }} / dashboard
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [0,1,2,3,4,5,6,7,8,9]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute path & existence
        id: meta
        run: |
          DIR="task_${{ matrix.task }}/dashboard"
          echo "dir=$DIR" >> "$GITHUB_OUTPUT"
          if [ -d "$DIR" ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Skip (folder not found)
        if: steps.meta.outputs.exists != 'true'
        run: echo "Skipping ${{ steps.meta.outputs.dir }} (not found)."

      - name: Use Node.js 20
        if: steps.meta.outputs.exists == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ steps.meta.outputs.dir }}/package-lock.json

      - name: Install deps
        if: steps.meta.outputs.exists == 'true'
        working-directory: ${{ steps.meta.outputs.dir }}
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # Optionnel : build si nécessaire
      # - name: Build
      #   if: steps.meta.outputs.exists == 'true'
      #   working-directory: ${{ steps.meta.outputs.dir }}
      #   run: npm run build

      - name: Run tests
        if: steps.meta.outputs.exists == 'true'
        env:
          CI: "true"
          COLUMNS: "120"   # évite le bug de reporter Jest sous TTY étroit
        working-directory: ${{ steps.meta.outputs.dir }}
        run: npm test -- --watchAll=false
        # Alternative plus silencieuse :
        # run: npm test -- --watchAll=false --reporters=summary

      - name: Upload coverage
        if: steps.meta.outputs.exists == 'true'
        uses: codecov/codecov-action@v3
